DROP TABLE HT_MAIN CASCADE CONSTRAINTS;

CREATE TABLE HT_MAIN
(
  username      VARCHAR2(16)              NOT NULL,
  password       VARCHAR2(20)              NOT NULL,
  ACCT_NO      VARCHAR2(16)              NOT NULL,
  PKG_ID       VARCHAR2(20)              NOT NULL,
  PROD_ID      VARCHAR2(20),
  FILE_PATH     varchar2(60),
  FILE_NAME     VARCHAR2(60),
  FILE_TYPE     VARCHAR2(10)
); 

COMMENT ON TABLE HT_MAIN IS '��ͬ������';

COMMENT ON COLUMN HT_MAIN.ACCT_NO IS '���׺�';

COMMENT ON COLUMN HT_MAIN.PKG_ID IS '���ʰ���';

COMMENT ON COLUMN HT_MAIN.PROD_ID IS '��Ŀ���';

COMMENT ON COLUMN HT_MAIN.FILE_PATH IS '�ļ�·��';

COMMENT ON COLUMN HT_MAIN.FILE_NAME IS '�ļ���';

COMMENT ON COLUMN HT_MAIN.FILE_TYPE IS '�ļ�����';
 
 CREATE UNIQUE INDEX INDEX_HT_MAIN ON HT_MAIN(ACCT_NO);